//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVirtualWaterFight.wsffWebAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsffWebAPI.WFStatsSoap")]
    public interface WFStatsSoap {
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.RegisterResponse Register(TestVirtualWaterFight.wsffWebAPI.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogNewGame", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.LogNewGameResponse LogNewGame(TestVirtualWaterFight.wsffWebAPI.LogNewGameRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogGameStats", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.LogGameStatsResponse LogGameStats(TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerTime", ReplyAction="*")]
        System.DateTime GetServerTime();
        
        // CODEGEN: Generating message contract since element name GetRegisterFightManagersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegisterFightManagers", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersResponse GetRegisterFightManagers(TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameIds", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.GetGameIdsResponse GetGameIds(TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameStats", ReplyAction="*")]
        TestVirtualWaterFight.wsffWebAPI.GetGameStatsResponse GetGameStats(TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(TestVirtualWaterFight.wsffWebAPI.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fightManagerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string operatorEmail;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string fightManagerId, string fightManagerName, string operatorName, string operatorEmail) {
            this.fightManagerId = fightManagerId;
            this.fightManagerName = fightManagerName;
            this.operatorName = operatorName;
            this.operatorEmail = operatorEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(TestVirtualWaterFight.wsffWebAPI.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogNewGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogNewGame", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.LogNewGameRequestBody Body;
        
        public LogNewGameRequest() {
        }
        
        public LogNewGameRequest(TestVirtualWaterFight.wsffWebAPI.LogNewGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogNewGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime start;
        
        public LogNewGameRequestBody() {
        }
        
        public LogNewGameRequestBody(string fightManagerId, int gameId, System.DateTime start) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
            this.start = start;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogNewGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogNewGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.LogNewGameResponseBody Body;
        
        public LogNewGameResponse() {
        }
        
        public LogNewGameResponse(TestVirtualWaterFight.wsffWebAPI.LogNewGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogNewGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogNewGameResult;
        
        public LogNewGameResponseBody() {
        }
        
        public LogNewGameResponseBody(string LogNewGameResult) {
            this.LogNewGameResult = LogNewGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogGameStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogGameStats", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequestBody Body;
        
        public LogGameStatsRequest() {
        }
        
        public LogGameStatsRequest(TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogGameStatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public wfssWebAPI.GameStats stats;
        
        public LogGameStatsRequestBody() {
        }
        
        public LogGameStatsRequestBody(string fightManagerId, int gameId, wfssWebAPI.GameStats stats) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
            this.stats = stats;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogGameStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogGameStatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.LogGameStatsResponseBody Body;
        
        public LogGameStatsResponse() {
        }
        
        public LogGameStatsResponse(TestVirtualWaterFight.wsffWebAPI.LogGameStatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogGameStatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogGameStatsResult;
        
        public LogGameStatsResponseBody() {
        }
        
        public LogGameStatsResponseBody(string LogGameStatsResult) {
            this.LogGameStatsResult = LogGameStatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegisterFightManagersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegisterFightManagers", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequestBody Body;
        
        public GetRegisterFightManagersRequest() {
        }
        
        public GetRegisterFightManagersRequest(TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRegisterFightManagersRequestBody {
        
        public GetRegisterFightManagersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegisterFightManagersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegisterFightManagersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersResponseBody Body;
        
        public GetRegisterFightManagersResponse() {
        }
        
        public GetRegisterFightManagersResponse(TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRegisterFightManagersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.ArrayOfString GetRegisterFightManagersResult;
        
        public GetRegisterFightManagersResponseBody() {
        }
        
        public GetRegisterFightManagersResponseBody(TestVirtualWaterFight.wsffWebAPI.ArrayOfString GetRegisterFightManagersResult) {
            this.GetRegisterFightManagersResult = GetRegisterFightManagersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameIds", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequestBody Body;
        
        public GetGameIdsRequest() {
        }
        
        public GetGameIdsRequest(TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameIdsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        public GetGameIdsRequestBody() {
        }
        
        public GetGameIdsRequestBody(string fightManagerId) {
            this.fightManagerId = fightManagerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameIdsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetGameIdsResponseBody Body;
        
        public GetGameIdsResponse() {
        }
        
        public GetGameIdsResponse(TestVirtualWaterFight.wsffWebAPI.GetGameIdsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameIdsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.ArrayOfInt GetGameIdsResult;
        
        public GetGameIdsResponseBody() {
        }
        
        public GetGameIdsResponseBody(TestVirtualWaterFight.wsffWebAPI.ArrayOfInt GetGameIdsResult) {
            this.GetGameIdsResult = GetGameIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameStats", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequestBody Body;
        
        public GetGameStatsRequest() {
        }
        
        public GetGameStatsRequest(TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        public GetGameStatsRequestBody() {
        }
        
        public GetGameStatsRequestBody(string fightManagerId, int gameId) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameStatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestVirtualWaterFight.wsffWebAPI.GetGameStatsResponseBody Body;
        
        public GetGameStatsResponse() {
        }
        
        public GetGameStatsResponse(TestVirtualWaterFight.wsffWebAPI.GetGameStatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wfssWebAPI.GameStats[] GetGameStatsResult;
        
        public GetGameStatsResponseBody() {
        }
        
        public GetGameStatsResponseBody(wfssWebAPI.GameStats[] GetGameStatsResult) {
            this.GetGameStatsResult = GetGameStatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFStatsSoapChannel : TestVirtualWaterFight.wsffWebAPI.WFStatsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFStatsSoapClient : System.ServiceModel.ClientBase<TestVirtualWaterFight.wsffWebAPI.WFStatsSoap>, TestVirtualWaterFight.wsffWebAPI.WFStatsSoap {
        
        public WFStatsSoapClient() {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFStatsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.RegisterResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.Register(TestVirtualWaterFight.wsffWebAPI.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string fightManagerId, string fightManagerName, string operatorName, string operatorEmail) {
            TestVirtualWaterFight.wsffWebAPI.RegisterRequest inValue = new TestVirtualWaterFight.wsffWebAPI.RegisterRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.RegisterRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.fightManagerName = fightManagerName;
            inValue.Body.operatorName = operatorName;
            inValue.Body.operatorEmail = operatorEmail;
            TestVirtualWaterFight.wsffWebAPI.RegisterResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.LogNewGameResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.LogNewGame(TestVirtualWaterFight.wsffWebAPI.LogNewGameRequest request) {
            return base.Channel.LogNewGame(request);
        }
        
        public string LogNewGame(string fightManagerId, int gameId, System.DateTime start) {
            TestVirtualWaterFight.wsffWebAPI.LogNewGameRequest inValue = new TestVirtualWaterFight.wsffWebAPI.LogNewGameRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.LogNewGameRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            inValue.Body.start = start;
            TestVirtualWaterFight.wsffWebAPI.LogNewGameResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).LogNewGame(inValue);
            return retVal.Body.LogNewGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.LogGameStatsResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.LogGameStats(TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequest request) {
            return base.Channel.LogGameStats(request);
        }
        
        public string LogGameStats(string fightManagerId, int gameId, wfssWebAPI.GameStats stats) {
            TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequest inValue = new TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.LogGameStatsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            inValue.Body.stats = stats;
            TestVirtualWaterFight.wsffWebAPI.LogGameStatsResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).LogGameStats(inValue);
            return retVal.Body.LogGameStatsResult;
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.GetRegisterFightManagers(TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequest request) {
            return base.Channel.GetRegisterFightManagers(request);
        }
        
        public TestVirtualWaterFight.wsffWebAPI.ArrayOfString GetRegisterFightManagers() {
            TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequest inValue = new TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersRequestBody();
            TestVirtualWaterFight.wsffWebAPI.GetRegisterFightManagersResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).GetRegisterFightManagers(inValue);
            return retVal.Body.GetRegisterFightManagersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.GetGameIdsResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.GetGameIds(TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequest request) {
            return base.Channel.GetGameIds(request);
        }
        
        public TestVirtualWaterFight.wsffWebAPI.ArrayOfInt GetGameIds(string fightManagerId) {
            TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequest inValue = new TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.GetGameIdsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            TestVirtualWaterFight.wsffWebAPI.GetGameIdsResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).GetGameIds(inValue);
            return retVal.Body.GetGameIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestVirtualWaterFight.wsffWebAPI.GetGameStatsResponse TestVirtualWaterFight.wsffWebAPI.WFStatsSoap.GetGameStats(TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequest request) {
            return base.Channel.GetGameStats(request);
        }
        
        public wfssWebAPI.GameStats[] GetGameStats(string fightManagerId, int gameId) {
            TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequest inValue = new TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequest();
            inValue.Body = new TestVirtualWaterFight.wsffWebAPI.GetGameStatsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            TestVirtualWaterFight.wsffWebAPI.GetGameStatsResponse retVal = ((TestVirtualWaterFight.wsffWebAPI.WFStatsSoap)(this)).GetGameStats(inValue);
            return retVal.Body.GetGameStatsResult;
        }
    }
}
