//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.wfssWebAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStats", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimestampField;
        
        private Server.wfssWebAPI.PossibleGameStates GameStatusField;
        
        private int CurrentNumberOfPlayersField;
        
        private int LargestNumberOfPlayersField;
        
        private int NumberOfBalloonsThrownField;
        
        private int NumberOfBalloonsThatHitField;
        
        private int AmountOfWaterThrownField;
        
        private int AmountOfWaterThatHitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Server.wfssWebAPI.PossibleGameStates GameStatus {
            get {
                return this.GameStatusField;
            }
            set {
                if ((this.GameStatusField.Equals(value) != true)) {
                    this.GameStatusField = value;
                    this.RaisePropertyChanged("GameStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CurrentNumberOfPlayers {
            get {
                return this.CurrentNumberOfPlayersField;
            }
            set {
                if ((this.CurrentNumberOfPlayersField.Equals(value) != true)) {
                    this.CurrentNumberOfPlayersField = value;
                    this.RaisePropertyChanged("CurrentNumberOfPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LargestNumberOfPlayers {
            get {
                return this.LargestNumberOfPlayersField;
            }
            set {
                if ((this.LargestNumberOfPlayersField.Equals(value) != true)) {
                    this.LargestNumberOfPlayersField = value;
                    this.RaisePropertyChanged("LargestNumberOfPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumberOfBalloonsThrown {
            get {
                return this.NumberOfBalloonsThrownField;
            }
            set {
                if ((this.NumberOfBalloonsThrownField.Equals(value) != true)) {
                    this.NumberOfBalloonsThrownField = value;
                    this.RaisePropertyChanged("NumberOfBalloonsThrown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumberOfBalloonsThatHit {
            get {
                return this.NumberOfBalloonsThatHitField;
            }
            set {
                if ((this.NumberOfBalloonsThatHitField.Equals(value) != true)) {
                    this.NumberOfBalloonsThatHitField = value;
                    this.RaisePropertyChanged("NumberOfBalloonsThatHit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int AmountOfWaterThrown {
            get {
                return this.AmountOfWaterThrownField;
            }
            set {
                if ((this.AmountOfWaterThrownField.Equals(value) != true)) {
                    this.AmountOfWaterThrownField = value;
                    this.RaisePropertyChanged("AmountOfWaterThrown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AmountOfWaterThatHit {
            get {
                return this.AmountOfWaterThatHitField;
            }
            set {
                if ((this.AmountOfWaterThatHitField.Equals(value) != true)) {
                    this.AmountOfWaterThatHitField = value;
                    this.RaisePropertyChanged("AmountOfWaterThatHit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PossibleGameStates", Namespace="http://tempuri.org/")]
    public enum PossibleGameStates : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Won = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wfssWebAPI.WFStatsSoap")]
    public interface WFStatsSoap {
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        Server.wfssWebAPI.RegisterResponse Register(Server.wfssWebAPI.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogNewGame", ReplyAction="*")]
        Server.wfssWebAPI.LogNewGameResponse LogNewGame(Server.wfssWebAPI.LogNewGameRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogGameStats", ReplyAction="*")]
        Server.wfssWebAPI.LogGameStatsResponse LogGameStats(Server.wfssWebAPI.LogGameStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerTime", ReplyAction="*")]
        System.DateTime GetServerTime();
        
        // CODEGEN: Generating message contract since element name GetRegisterFightManagersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegisterFightManagers", ReplyAction="*")]
        Server.wfssWebAPI.GetRegisterFightManagersResponse GetRegisterFightManagers(Server.wfssWebAPI.GetRegisterFightManagersRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameIds", ReplyAction="*")]
        Server.wfssWebAPI.GetGameIdsResponse GetGameIds(Server.wfssWebAPI.GetGameIdsRequest request);
        
        // CODEGEN: Generating message contract since element name fightManagerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameStats", ReplyAction="*")]
        Server.wfssWebAPI.GetGameStatsResponse GetGameStats(Server.wfssWebAPI.GetGameStatsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Server.wfssWebAPI.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fightManagerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string operatorEmail;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string fightManagerId, string fightManagerName, string operatorName, string operatorEmail) {
            this.fightManagerId = fightManagerId;
            this.fightManagerName = fightManagerName;
            this.operatorName = operatorName;
            this.operatorEmail = operatorEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Server.wfssWebAPI.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogNewGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogNewGame", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.LogNewGameRequestBody Body;
        
        public LogNewGameRequest() {
        }
        
        public LogNewGameRequest(Server.wfssWebAPI.LogNewGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogNewGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime start;
        
        public LogNewGameRequestBody() {
        }
        
        public LogNewGameRequestBody(string fightManagerId, int gameId, System.DateTime start) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
            this.start = start;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogNewGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogNewGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.LogNewGameResponseBody Body;
        
        public LogNewGameResponse() {
        }
        
        public LogNewGameResponse(Server.wfssWebAPI.LogNewGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogNewGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogNewGameResult;
        
        public LogNewGameResponseBody() {
        }
        
        public LogNewGameResponseBody(string LogNewGameResult) {
            this.LogNewGameResult = LogNewGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogGameStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogGameStats", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.LogGameStatsRequestBody Body;
        
        public LogGameStatsRequest() {
        }
        
        public LogGameStatsRequest(Server.wfssWebAPI.LogGameStatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogGameStatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Server.wfssWebAPI.GameStats stats;
        
        public LogGameStatsRequestBody() {
        }
        
        public LogGameStatsRequestBody(string fightManagerId, int gameId, Server.wfssWebAPI.GameStats stats) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
            this.stats = stats;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogGameStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogGameStatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.LogGameStatsResponseBody Body;
        
        public LogGameStatsResponse() {
        }
        
        public LogGameStatsResponse(Server.wfssWebAPI.LogGameStatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogGameStatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogGameStatsResult;
        
        public LogGameStatsResponseBody() {
        }
        
        public LogGameStatsResponseBody(string LogGameStatsResult) {
            this.LogGameStatsResult = LogGameStatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegisterFightManagersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegisterFightManagers", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetRegisterFightManagersRequestBody Body;
        
        public GetRegisterFightManagersRequest() {
        }
        
        public GetRegisterFightManagersRequest(Server.wfssWebAPI.GetRegisterFightManagersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRegisterFightManagersRequestBody {
        
        public GetRegisterFightManagersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegisterFightManagersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegisterFightManagersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetRegisterFightManagersResponseBody Body;
        
        public GetRegisterFightManagersResponse() {
        }
        
        public GetRegisterFightManagersResponse(Server.wfssWebAPI.GetRegisterFightManagersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRegisterFightManagersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Server.wfssWebAPI.ArrayOfString GetRegisterFightManagersResult;
        
        public GetRegisterFightManagersResponseBody() {
        }
        
        public GetRegisterFightManagersResponseBody(Server.wfssWebAPI.ArrayOfString GetRegisterFightManagersResult) {
            this.GetRegisterFightManagersResult = GetRegisterFightManagersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameIds", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetGameIdsRequestBody Body;
        
        public GetGameIdsRequest() {
        }
        
        public GetGameIdsRequest(Server.wfssWebAPI.GetGameIdsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameIdsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        public GetGameIdsRequestBody() {
        }
        
        public GetGameIdsRequestBody(string fightManagerId) {
            this.fightManagerId = fightManagerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameIdsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetGameIdsResponseBody Body;
        
        public GetGameIdsResponse() {
        }
        
        public GetGameIdsResponse(Server.wfssWebAPI.GetGameIdsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameIdsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Server.wfssWebAPI.ArrayOfInt GetGameIdsResult;
        
        public GetGameIdsResponseBody() {
        }
        
        public GetGameIdsResponseBody(Server.wfssWebAPI.ArrayOfInt GetGameIdsResult) {
            this.GetGameIdsResult = GetGameIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameStats", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetGameStatsRequestBody Body;
        
        public GetGameStatsRequest() {
        }
        
        public GetGameStatsRequest(Server.wfssWebAPI.GetGameStatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fightManagerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gameId;
        
        public GetGameStatsRequestBody() {
        }
        
        public GetGameStatsRequestBody(string fightManagerId, int gameId) {
            this.fightManagerId = fightManagerId;
            this.gameId = gameId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameStatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Server.wfssWebAPI.GetGameStatsResponseBody Body;
        
        public GetGameStatsResponse() {
        }
        
        public GetGameStatsResponse(Server.wfssWebAPI.GetGameStatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Server.wfssWebAPI.GameStats[] GetGameStatsResult;
        
        public GetGameStatsResponseBody() {
        }
        
        public GetGameStatsResponseBody(Server.wfssWebAPI.GameStats[] GetGameStatsResult) {
            this.GetGameStatsResult = GetGameStatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFStatsSoapChannel : Server.wfssWebAPI.WFStatsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFStatsSoapClient : System.ServiceModel.ClientBase<Server.wfssWebAPI.WFStatsSoap>, Server.wfssWebAPI.WFStatsSoap {
        
        public WFStatsSoapClient() {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFStatsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFStatsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.RegisterResponse Server.wfssWebAPI.WFStatsSoap.Register(Server.wfssWebAPI.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string fightManagerId, string fightManagerName, string operatorName, string operatorEmail) {
            Server.wfssWebAPI.RegisterRequest inValue = new Server.wfssWebAPI.RegisterRequest();
            inValue.Body = new Server.wfssWebAPI.RegisterRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.fightManagerName = fightManagerName;
            inValue.Body.operatorName = operatorName;
            inValue.Body.operatorEmail = operatorEmail;
            Server.wfssWebAPI.RegisterResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.LogNewGameResponse Server.wfssWebAPI.WFStatsSoap.LogNewGame(Server.wfssWebAPI.LogNewGameRequest request) {
            return base.Channel.LogNewGame(request);
        }
        
        public string LogNewGame(string fightManagerId, int gameId, System.DateTime start) {
            Server.wfssWebAPI.LogNewGameRequest inValue = new Server.wfssWebAPI.LogNewGameRequest();
            inValue.Body = new Server.wfssWebAPI.LogNewGameRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            inValue.Body.start = start;
            Server.wfssWebAPI.LogNewGameResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).LogNewGame(inValue);
            return retVal.Body.LogNewGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.LogGameStatsResponse Server.wfssWebAPI.WFStatsSoap.LogGameStats(Server.wfssWebAPI.LogGameStatsRequest request) {
            return base.Channel.LogGameStats(request);
        }
        
        public string LogGameStats(string fightManagerId, int gameId, Server.wfssWebAPI.GameStats stats) {
            Server.wfssWebAPI.LogGameStatsRequest inValue = new Server.wfssWebAPI.LogGameStatsRequest();
            inValue.Body = new Server.wfssWebAPI.LogGameStatsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            inValue.Body.stats = stats;
            Server.wfssWebAPI.LogGameStatsResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).LogGameStats(inValue);
            return retVal.Body.LogGameStatsResult;
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.GetRegisterFightManagersResponse Server.wfssWebAPI.WFStatsSoap.GetRegisterFightManagers(Server.wfssWebAPI.GetRegisterFightManagersRequest request) {
            return base.Channel.GetRegisterFightManagers(request);
        }
        
        public Server.wfssWebAPI.ArrayOfString GetRegisterFightManagers() {
            Server.wfssWebAPI.GetRegisterFightManagersRequest inValue = new Server.wfssWebAPI.GetRegisterFightManagersRequest();
            inValue.Body = new Server.wfssWebAPI.GetRegisterFightManagersRequestBody();
            Server.wfssWebAPI.GetRegisterFightManagersResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).GetRegisterFightManagers(inValue);
            return retVal.Body.GetRegisterFightManagersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.GetGameIdsResponse Server.wfssWebAPI.WFStatsSoap.GetGameIds(Server.wfssWebAPI.GetGameIdsRequest request) {
            return base.Channel.GetGameIds(request);
        }
        
        public Server.wfssWebAPI.ArrayOfInt GetGameIds(string fightManagerId) {
            Server.wfssWebAPI.GetGameIdsRequest inValue = new Server.wfssWebAPI.GetGameIdsRequest();
            inValue.Body = new Server.wfssWebAPI.GetGameIdsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            Server.wfssWebAPI.GetGameIdsResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).GetGameIds(inValue);
            return retVal.Body.GetGameIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Server.wfssWebAPI.GetGameStatsResponse Server.wfssWebAPI.WFStatsSoap.GetGameStats(Server.wfssWebAPI.GetGameStatsRequest request) {
            return base.Channel.GetGameStats(request);
        }
        
        public Server.wfssWebAPI.GameStats[] GetGameStats(string fightManagerId, int gameId) {
            Server.wfssWebAPI.GetGameStatsRequest inValue = new Server.wfssWebAPI.GetGameStatsRequest();
            inValue.Body = new Server.wfssWebAPI.GetGameStatsRequestBody();
            inValue.Body.fightManagerId = fightManagerId;
            inValue.Body.gameId = gameId;
            Server.wfssWebAPI.GetGameStatsResponse retVal = ((Server.wfssWebAPI.WFStatsSoap)(this)).GetGameStats(inValue);
            return retVal.Body.GetGameStatsResult;
        }
    }
}
